sonar.projectName=Administrador Virtual Inteligente
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.*,**/*.spec.*
sonar.exclusions=**/*.test.*,**/*.spec.*,**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info,apps/api/coverage/lcov.info,packages/contracts/coverage/lcov.info
sonar.sourceEncoding=UTF-8
